### ISSUE TITLE
How different is it from Metatrader 4

### ISSUE THREAD

**Issue by FatCache** [slawekj/wolf#3]
Hey I'm currently running Metatrader 4 on Ubuntu via Wine. Is this tool superior to Metatrader 4? If so, how? I couldn't follow the explanation on the 'getting started page'

**Comment by slawekj** [comment]
Hey. In short, 99.9% of Wolf's code is designed to run on beefy servers, not desktop machines. Regular investors don't have to install anything on their desktops. They just open a web browser. This is giving Wolf an edge in being capable of processing a large volume of data. Far beyond what a desktop software could ever do. The only code that Wolf runs on a client side is part of a web user interface. Meta Trader and other tools are around for quite some time, well tested. Wolf is a new thing, not deployed publicly at the moment.

**Comment by FatCache** [comment]
So will Wolf come with its own algorithm/scripts for exchange? Major bulk of the FOREX trading system setting up algorithm and performing quick trades to match the real time data and fluctuations. If it doesn't come with it, the point of Wolf is basically to analyze huge chunk of historical data on beefy servers? Am I following it correctly?

**Comment by slawekj** [comment]
There are ethical an legal issues about publishing trading algorithms. The point of Wolf is not to take a risk for you, it is rather to provide "Trading as a Service", or whatever fancy name you want to have here. This is the way I would see this: you can push an "event" or a "rule" to Wolf, and that's it! You can use a Web UI or your own script to do so. You provide a trading algorithm, or a "risk" in a rule.

An event you push to Wolf should have a key and a numerical or categorical value, say "My friend got married" -> "True", or "My salary" -> "65k". A rule should use keys from events to trigger actions, an example: "My wedding rule 1" -> "if My friend got married is True and My salary >= 55k then buy a gift". And now, what Wolf gives you really is all the magic that happens behind the scenes to make this rule execute.

**Comment by FatCache** [comment]
Thanks a lot @slawekj I understand what the tool does exactly. I know you said it meant for big beefy servers but I'll be waiting one which can be installed on an i7 8gigs RAM computer and utilizes all the resource.
